CREATE TABLE COMMONS_COMMONS
(
    ID char(36) NOT NULL,
    SITE_ID varchar(99) NOT NULL,
    EMBEDDER varchar(24) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE COMMONS_COMMONS_POST
(
    COMMONS_ID char(36) references COMMONS_COMMONS(ID),
    POST_ID char(36) references COMMONS_POST(ID)
);

CREATE TABLE COMMONS_POST
(
    ID char(36) NOT NULL,
    CONTENT MEDIUMTEXT NOT NULL,
    CREATOR_ID varchar(99) NOT NULL,
    CREATED_DATE datetime NOT NULL,
    MODIFIED_DATE datetime NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE COMMONS_COMMENT
(
    ID char(36) NOT NULL,
    POST_ID char(36) NOT NULL,
    CONTENT MEDIUMTEXT NOT NULL,
    CREATOR_ID varchar(99) NOT NULL,
    CREATED_DATE datetime NOT NULL,
    MODIFIED_DATE datetime NOT NULL,
    PRIMARY KEY(ID)
);
