CREATE TABLE COURSEWALL_POST
(
    ID char(36) NOT NULL,
    SITE_ID varchar(99) NOT NULL,
    CONTENT MEDIUMTEXT NOT NULL,
    CREATOR_ID varchar(99) NOT NULL,
    CREATED_DATE datetime NOT NULL,
    MODIFIED_DATE datetime NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE COURSEWALL_COMMENT
(
    ID char(36) NOT NULL,
    POST_ID char(36) NOT NULL,
    CONTENT MEDIUMTEXT NOT NULL,
    CREATOR_ID varchar(99) NOT NULL,
    CREATED_DATE datetime NOT NULL,
    MODIFIED_DATE datetime NOT NULL,
    PRIMARY KEY(ID)
);
