CREATE TABLE COURSEWALL_WALL
(
    ID char(36) NOT NULL,
    SITE_ID varchar(99) NOT NULL,
    EMBEDDER varchar(24) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE COURSEWALL_WALL_POST
(
    WALL_ID char(36) references COURSEWALL_WALL(ID),
    POST_ID char(36) references COURSEWALL_POST(ID)
);

CREATE TABLE COURSEWALL_POST
(
    ID char(36) NOT NULL,
    CONTENT MEDIUMTEXT NOT NULL,
    CREATOR_ID varchar(99) NOT NULL,
    CREATED_DATE datetime NOT NULL,
    MODIFIED_DATE datetime NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE COURSEWALL_COMMENT
(
    ID char(36) NOT NULL,
    POST_ID char(36) NOT NULL,
    CONTENT MEDIUMTEXT NOT NULL,
    CREATOR_ID varchar(99) NOT NULL,
    CREATED_DATE datetime NOT NULL,
    MODIFIED_DATE datetime NOT NULL,
    PRIMARY KEY(ID)
);
